### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class com.facebook.thrift.transport.TSocket

### ISSUE THREAD

**Issue by xhrwp** [vesoft-inc/nebula-jdbc#33]
![image](https://user-images.githubusercontent.com/10394828/184796326-17e63cff-9ffb-4917-b7e2-bebbf9ed4433.png)

nebula-jdbc. version:3.0.0

**Comment by Young-Flash** [comment]
seems dependence missing, make sure you have download all the maven dependence into the project

**Comment by chenlinzhong** [comment]
+1 

version:3.0.0

java.lang.NoClassDefFoundError: Could not initialize class com.facebook.thrift.transport.TSocket
	at com.vesoft.nebula.client.graph.net.SyncConnection.open(SyncConnection.java:94)
	at com.vesoft.nebula.client.graph.net.RoundRobinLoadBalancer.ping(RoundRobinLoadBalancer.java:87)
	at com.vesoft.nebula.client.graph.net.RoundRobinLoadBalancer.updateServersStatus(RoundRobinLoadBalancer.java:73)
	at com.vesoft.nebula.client.graph.net.RoundRobinLoadBalancer.isServersOK(RoundRobinLoadBalancer.java:101)
	at com.vesoft.nebula.client.graph.net.ConnObjectPool.init(ConnObjectPool.java:93)
	at com.vesoft.nebula.client.graph.net.NebulaPool.init(NebulaPool.java:120)
	at com.vesoft.nebula.jdbc.NebulaConnection.initNebulaPool(NebulaConnection.java:104)
	at com.vesoft.nebula.jdbc.NebulaConnection.<init>(NebulaConnection.java:64)
	at com.vesoft.nebula.jdbc.NebulaDriver.connect(NebulaDriver.java:79)

**Comment by chenlinzhong** [comment]
[root]$ java -version 
java version "1.8.0_131"


Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class com.facebook.thrift.transport.TSocket
        at com.vesoft.nebula.client.graph.net.SyncConnection.open(SyncConnection.java:94)
        at com.vesoft.nebula.client.graph.net.RoundRobinLoadBalancer.ping(RoundRobinLoadBalancer.java:87)
        at com.vesoft.nebula.client.graph.net.RoundRobinLoadBalancer.updateServersStatus(RoundRobinLoadBalancer.java:73)
        at com.vesoft.nebula.client.graph.net.RoundRobinLoadBalancer.isServersOK(RoundRobinLoadBalancer.java:101)
        at com.vesoft.nebula.client.graph.net.ConnObjectPool.init(ConnObjectPool.java:93)
        at com.vesoft.nebula.client.graph.net.NebulaPool.init(NebulaPool.java:120)
        at com.vesoft.nebula.jdbc.NebulaConnection.initNebulaPool(NebulaConnection.java:107)
        at com.vesoft.nebula.jdbc.NebulaConnection.<init>(NebulaConnection.java:64)
        at com.vesoft.nebula.jdbc.NebulaDriver.connect(NebulaDriver.java:79)
        at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1652)
        at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1718)
        at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:915)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1389)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1385)
