### ISSUE TITLE
Cannot query 'show tags'

### ISSUE THREAD

**Issue by cdalexndr** [vesoft-inc/nebula-jdbc#56]
```
Caused by: java.sql.SQLException: Method executeQuery() can only execute nGql to query data, but the current nGql do not contains any query keyword in [match, lookup, go, fetch, find, subgraph], please modify your nGql or use executeUpdate(), execute().
	at com.vesoft.nebula.jdbc.statement.NebulaStatementImpl.checkReadOnly(NebulaStatementImpl.java:97)
	at com.vesoft.nebula.jdbc.statement.NebulaPreparedStatementImpl.executeQuery(NebulaPreparedStatementImpl.java:44)
	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:722)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:651)
```

**Comment by cdalexndr** [comment]
Duplciate of #42
